meta_data:
  script_path: run_scripts/td3bc_script.py
  exp_name: td3bc_hopper_me_v2_base
  description: Train an agent using TD3BC
  gpu: [0]
  num_workers: 1
  using_gpus: true
# -----------------------------------------------------------------------------
variables:
  seed: [0]

# -----------------------------------------------------------------------------
constants:
  dataset_name: 'hopper_me_v2'
  debug: false

  rl_trainer_params:
    num_epochs: 2000
    num_train_steps_per_train_call: 250
    num_steps_per_eval: 5000
    max_path_length: 1000
    batch_size: 256
    replay_buffer_size: 2000000

  td3_bc_params:
    discount: 0.99
    net_size: 256
    num_hidden_layers: 2

  env_specs:
    env_name: 'hopper'
    env_kwargs: {}
    env_num: 4 # This parameter define how many vec envs are created
    eval_env_seed: 0 # These two seeds are no longer needed since in our implementation we makes all seeds the same, see the script file, however you can change the script to make it valid
    training_env_seed: 0
    normalize_obs: true